name: Build and Deploy to DockerHub and EC2

on:
  push:
    branches:
      - main
    paths:
      - frontend/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: eviltwin7648/foodcare-frontend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull eviltwin7648/foodcare-frontend:latest
            sudo docker stop foodcare-frontend || true
            sudo docker rm foodcare-frontend || true
            sudo docker run -e VITE_API_URL=https://api.sharemeal.vishalrai.tech -d --name foodcare-frontend -p 4173:4173 eviltwin7648/foodcare-frontend:latest



